[package]
name = "entropy-mesh"
version = "0.1.0"
edition = "2021"

[dependencies]
ark-std = "0.4.0"
crdts = "7.3.2"
etf-crypto-primitives = { git = "https://github.com/ideal-lab5/etf-sdk.git" }
rand_chacha = "0.3.1"
sha2 = "0.10.8"
w3f-bls = "0.1.4"
